spring:
  threads:
    virtual:
      enabled: true
  application:
    name: texas-holdem

  datasource:
    url: jdbc:postgresql://localhost:5432/texas_holdem
    username: admin
    password: 0IzRxaAlqqxNCYg
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 2000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update        # dev만. 운영은 validate 권장
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
        default_batch_fetch_size: 100

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    redis:
      repositories:
        enabled: false

  redis:
    host: localhost
    port: 6379
    timeout: 2s
    lettuce:
      pool:
        max-active: 32
        max-idle: 16
        min-idle: 4
      shutdown-timeout: 2s

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        includ
